# Generated by Django 5.2.14 on 2026-05-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=150, verbose_name='Nom/Référence du patient')),
                ('age_patient', models.PositiveIntegerField(verbose_name='Âge du patient')),
                ('sexe_patient', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe du patient')),
                ('zone', models.CharField(max_length=150, verbose_name='Zone géographique')),
                ('symptomes_saisis', models.TextField(verbose_name='Symptômes saisis')),
                ('diagnostic_retenu', models.CharField(max_length=200, verbose_name='Diagnostic retenu/Maladie')),
                ('score_diagnostic', models.PositiveIntegerField(default=0, verbose_name='Score de certitude (%)')),
                ('signes_danger', models.TextField(blank=True, verbose_name='Signes de danger critiques détectés')),
                ('date_consultation', models.DateTimeField(verbose_name='Date et heure de la consultation locale')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de synchronisation serveur')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Agent de santé référent')),
            ],
            options={
                'verbose_name': 'Consultation Médicale',
                'verbose_name_plural': 'Consultations Médicales',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
