# Generated by Django 5.2.14 on 2026-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='poids_patient',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids du patient (kg)'),
        ),
    ]
